apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.20.10-10.0.20.20

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: webservers
  namespace: metallb-system
