apiVersion: v1
kind: Service
metadata:
  name: career-website-service
spec:
  type: LoadBalancer
  selector:
    app: angrybraindev-career-website
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80